language: python

branches:
  only:
    - travisCI

services:
    - docker

os: 
  - linux

jobs:
  include:
    - name: "spm"
      env: DESIGN=spm
    - name: "APU"
      env: DESIGN=APU
    - name: "PPU"
      env: DESIGN=PPU
    - name: "usb"
      env: DESIGN=usb
    - name: "xtea"
      env: DESIGN=xtea
    - name: "md5"
      env: DESIGN=md5

install:
  - sh ./travisBuild.sh

script: 
  - sh ./travisTest.sh $DESIGN  