language: python

branches:
  only:
    - travisCI

services:
    - docker

os: 
  - linux

jobs:
  include:
    - stage: build
      script:
        - sh ./travisBuild.sh
    - stage: test
      script: ./travisTest.sh spm
    - # stage name not required
      script: ./travisTest.sh xtea  
    - # stage name not required
      script: ./travisTest.sh APU