language: python

branches:
  only:
    - travisCI

services:
    - docker

os: linux

jobs:
  include:
    - stage: build
      install:
        - sh ./travisBuild.sh
      env: DESIGN=spm 
    - name: "APU"
      env: DESIGN=APU
    - name: "PPU"
      env: DESIGN=PPU
    - name: "usb"
      env: DESIGN=usb
    - name: "xtea"
      env: DESIGN=xtea
script: sh ./travisTest.sh $DESIGN  