language: python

branches:
  only:
    - travisCI

services:
    - docker

os: 
  - linux
  - osx
  
jobs:
  include:
    - stage: build
      install:
        - sh ./travisBuild.sh
      script:
        - sh ./travisTest.sh spm
    - stage: test
      - name: "APU"
        install:
          - sh ./travisBuild.sh
        env: DESIGN=APU
      - name: "PPU"
        install:
          - sh ./travisBuild.sh
        env: DESIGN=PPU
      - name: "usb"
        install:
          - sh ./travisBuild.sh
        env: DESIGN=usb
      - name: "xtea"
        install:
          - sh ./travisBuild.sh
        env: DESIGN=xtea
     script: sh ./travisTest.sh $DESIGN  