branches:
  only:
    - travisCI

services:
    - docker

os: 
  - linux

jobs:
  include:
    - stage: build    
      env: TEST_SET=fastestTestSet
      install:
        - sh travisCI/travisBuild.sh
      script: 
        - sh travisCI/travisTest.sh travisCI $TEST_SET  