language: python

branches:
  only:
    - travisCI

services:
    - docker

os: linux

jobs:
  include:
    - stage: build
      install:
        - sh ./travisBuild.sh
      script:
        - sh ./travisTest.sh spm