language: python

branches:
  only:
    - travisCI

services:
    - docker

os: 
  - linux
  - osx

jobs:
  include:
    - name: "Fastest Test Set"
      env: TEST_SET=fastestTestSet
    - name: "Typical Test Set"
      env: TEST_SET=typicalTestSet
    - name: "Slowest Test Set 1"
      env: TEST_SET=slowestTestSet
    
install:
  - sh travisCI/travisBuild.sh

script: 
  - sh travisCI/travisTest.sh travisCI $TEST_SET  