language: python

branches:
  only:
    - travisCI
    - develop

services:
    - docker

os: 
  - linux

jobs:
  include:
    - name: "Fastest Test Set"
      env: TEST_SET=fastestTestSet
    
install:
  - sh travisCI/travisBuild.sh

script: 
  - sh travisCI/travisTest.sh travisCI $TEST_SET  